id: P002897
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG4255
  title: གྲུབ་མཐའི་རྣམ་བཞག་ལེགས་བཤད་འདོད་འཇོ་ས་ལམ་གྱི་རྣམ་བཞག་ཤེལ་དཀར་མེ་ལོང་དོགས་གཅོད་རྡོ་རྗེའི་གཟེགས་མ་ཁྱབ་སྒོ་རེ་གཉིས་ཀྱི་རེ་མིག་
  author: ''
  volumes: {}
