id: P002897
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG4255
  title: གྲུབ་མཐའི་རྣམ་བཞག་ལེགས་བཤད་འདོད་འཇོ་ས་ལམ་གྱི་རྣམ་བཞག་ཤེལ་དཀར་མེ་ལོང་དོགས་གཅོད་རྡོ་རྗེའི་གཟེགས་མ་ཁྱབ་སྒོ་རེ་གཉིས་ཀྱི་རེ་མིག་
  author: ''
  volumes:
    15392b9a64864c3cb83d638002cd3f35:
      image_group_id: I1KG4979
      title: ''
      volume_number: 1
      total_pages: 234
      base_file: v001.txt
